### ISSUE TITLE
Can't determine exponent directory

### ISSUE THREAD

**Issue by mauroporrasp** [expo/xdl#19]
When trying to detach a fresh app. I'm usind macOS. Thanks.

<img width="1070" alt="screen shot 2017-12-14 at 07 20 19" src="https://user-images.githubusercontent.com/167700/33992129-734cf860-e09f-11e7-9512-bd077578339e.png">

This is my dir structure:
<img width="527" alt="screen shot 2017-12-14 at 07 23 47" src="https://user-images.githubusercontent.com/167700/33992233-cda655ea-e09f-11e7-99b0-b582722d7ba2.png">

**Comment by mtrushin** [comment]
same here: https://github.com/expo/xdl/issues/19

**Comment by mauroporrasp** [comment]
I made it work issuing:
`EXPO_UNIVERSE_DIR=.expo EXPO_DEBUG=true exp detach`

**Comment by terribleben** [comment]
Thanks for the report, sorry for the delay here. We're working on resolving this now and are tracking it over at the [other repo](https://github.com/expo/xdl/issues/19).
