### ISSUE TITLE
exp.host server

### ISSUE THREAD

**Issue by acornejo** [expo/xdl#3]
I am new to exponent (looks awesome btw), and wanted to learn a bit more beyond what is already available in the documentation.

Here are some questions that popped to mind when I learned about exponent:

1) Where is the source code for the server that provides the .bundle files to the exponent app? (perhaps this part is not open source?)
2) If I develop a standalone app using exponent, can I replace exp.host with something else? (i.e. can I serve my own bundle without relying on the exponent servers?).
3) Does the manifest include a hash of the current bundle, or is there some other mechanism where the exponent app will avoid downloading the bundle again if it already has the newest version cached?

I would be happy to contribute a pull-request to update the exponent documentation to include some of this information, but first I need to get answers myself ;)

**Comment by matthewyt** [comment]
I was also wondering the same thing, but I think this is part of the exp project not xdl. It would be nice to have documentation on exactly works or have the ability to host this on my own servers to increase reliability of an app.

**Comment by jesseruder** [comment]
@acornejo sorry about the slow response! haven't checked this repo in a while.

1. The server isn't open source right now, you're correct.
2. We're planning on making it easier to self host eventually but it hasn't been a priority to us so far. There's nothing inherently tying the clients to our server - you could host the manifest on your server and it would work, rnplay actually does this right now https://github.com/rnplay/rnplay-web/blob/master/app/controllers/apps_controller.rb#L48. Our tooling isn't set up to let you build shell apps with `exp build` that target another server, but if you build from source you can https://github.com/exponent/exponent#standalone-apps.
3. We use HTTP level caching for the manifest and the bundle. We use ETags for the manifest and immutable urls for the bundle. So if the bundle url in the manifest hasn't change we won't fetch it again. But again this is all at the HTTP level so a different server could use a different strategy.

Hope that all makes sense!
