### ISSUE TITLE
How to ignore SSL self-signed errors

### ISSUE THREAD

**Issue by thebetterjort** [expo/xdl#5]
yarn start v0.21.3
$ react-native-scripts start 
Starting packager...
Error starting packager: Error: Unable to perform cache refresh for /home/username/.cache/expo/versions.json: Error: self signed certificate in certificate chain
    at /xdl/src/tools/FsCache.js:101:15
    at throw (native)
    at step (/home/username/Documents/my-app/node_modules/xdl/build/tools/FsCache.js:32:191)
    at /home/username/Documents/my-app/node_modules/xdl/build/tools/FsCache.js:32:402
error Command failed with exit code 1.

**Comment by dikaiosune** [comment]
Looks like this was covered in https://github.com/expo/xde/issues/85 ?
