### ISSUE TITLE
More informative log message when logging functions, objects, and other

### ISSUE THREAD

**Issue by brentvatne** [expo/xdl#9]
```
function someFunc(a, b) {
  // some code
}
```

- `console.log(someFunc)` currently prints `null`
- Ideally it would print `function someFunc(a, b) { }`
- It should also print anonymous functions nicely

More info: https://github.com/react-community/create-react-native-app/issues/168

**Comment by BrennerSpear** [comment]
+1

This was confusing the hell out of me.

Also, any console log with ```this``` in it doesn't even get logged.

```
console.log('hello world')
console.log('hello mars', this)

#logs:
hello world

**Comment by brentvatne** [comment]
Moved this to https://github.com/expo/expo/issues/168
